### ISSUE TITLE
Add support for repo weights

### ISSUE THREAD

**Issue by jakegut** [indeedeng/Mariner-Issue-Collector#6]
From the README:
> Weight is not currently used, but could be used to put the issues in order of importance to you

Implementing weights for the repositories would be nice to have and should be easy to do. I suppose we can sort the keys based on it's value and let Mariner run, resulting in issues sorted based on it's repository weight. 

I'd like to implement this.

**Comment by DuaneOBrien** [comment]
Thanks for capturing this in an issue!

Sorting the keys by values won't work in this case because of how Mariner queries for issues. Mariner makes one GitHub API call per 1000 repos per label ("Show me all issues labeled Hacktoberfest in any of these 1000 repositories). The issues themselves are returned in a default sort order of "most recently filed". The end result is you'll get back a long list of issues sorted by ascending age, regardless of repo.

Probably the way to do this would be to sort the issues in convertToRecord such that the repos are for sure in order by descending weight.

**Comment by DuaneOBrien** [comment]
@jakeryang do you still want to take this one on?

**Comment by jakegut** [comment]
Yes I can! I actually have something on a branch that resolves this. I'll open a PR for it.
